language: java
jdk:
  - oraclejdk8
notification:
  email:
    recipients:
      - song_s@ctrip.com,zhanglea@ctrip.com
    on_success: always
    on_failure: always

before_script:
  - echo "MAVEN_OPTS='-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m'" > ~/.mavenrc
  
before_install:
  - pip install --user codecov

after_success:
  - mvn clean test jacoco:report coveralls:report
  - codecov

branches:
  only:
    - master
    
env:
  global:
    - secure: "MArmEt8y5GtOZRBkqUHwR7BXRxVyXtxCvSIELM0sLk3dHFe22P21YdCx4bagWPmMxkRLMklJdL50m7rc0rRJOPWlczPIIYwhAwnPEuFcFi/hiboEbpNLekV5kqKVmKW0/WWCU59ReV2qVF18e+3uHvAGuu+rQhfTyYsoZ/AUTj+GkoC/z5/ccFvvqsG5mWCKrypmWBdw9xE9SooLwE0/ET/ldENHxmJjHgaIsVob5Hi1IT3duNYK5XjH60nWHc5ozJSWvm03jz98V02EWWGYmts9HGpA89d4G2HlmyzfzkdoAZJKMUbuCc1jSSL2xEIkZ75NIE9SMz5frSNZfSb1dTRyvDHoXrYpugt14TC6gbHNkyX9pjHlpUYQ6PiwICS4EbkSzrlUfctbBW+qY4TbKlRxq3HYyIcU4QnwPzr2AVT/oiCyOfr5Yrr2QZbToDdJzS2Z81CJPVr618F6wGBqIUtv4RXSyRJUsYbVQCJUXnCd4zn5O2JmxBngtNOreLWSY8h4QjH5cB4ii5YZLcQv90VoiWjUNvaUu1+CUxk312ra4Mc0oCqs2RyTEKCZ7ishV5W3Zr1uz0TY48BgPoQ3I+BbEzQAq0tYRi95kQJm4QlEYx9sk+Bied9gIJJRVoLcBIk29Un6wxChB1SVucWqHBcT290OziZcGDjpBdbeQMQ="
    - "MAVEN_OPTS=-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m"

addons:
  coverity_scan:
    project:
      name: "ctripcorp/apollo"
      description: "Build submitted via Travis CI"
    notification_email: song_s@ctrip.com,zhanglea@ctrip.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: master

cache:
  directories:
    - $HOME/.m2
