version: '2'

services:
  apollo-configservice:
    image: apollo-configservice
    container_name: apollo-configservice
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - /tmp/logs:/opt/logs
    links:
      - db

  apollo-adminservice:
    image: apollo-adminservice
    container_name: apollo-adminservice
    restart: always
    depends_on:
      - db
    ports:
      - "8090:8090"
    volumes:
      - /tmp/logs:/opt/logs
    links:
      - db

  apollo-portal:
    image: apollo-portal
    container_name: apollo-portal
    restart: always
    depends_on:
      - db
    ports:
      - "9090:8080"
    volumes:
      - /tmp/logs:/opt/logs
    links:
      - db

  apollo-spring-boot-sample:
    image: apollo-spring-boot-sample
    container_name: apollo-spring-boot-sample
    restart: always
    depends_on:
      - apollo-configservice
      - apollo-adminservice
      - apollo-portal
    ports:
      - "9190:9090"
    volumes:
      - /tmp:/tmp

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /var/data/mysql:/var/lib/mysql