spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003173
  
server:
  port: 8080
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 
