spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  resources:
    cache:
      cachecontrol:
        max-age: 3600

server:
  port: 8080
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


